package com.ragnarok.auth.common.exception

class InitializingFailException(cause: Throwable) : RuntimeException(cause)
